/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ./public/restaurant.glb 
Author: Home Design 3D (https://sketchfab.com/homedesign3d)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/restaurant-23a4f8c9eac64c4d9031a27aacbf46dd
Title: Restaurant
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Restaurant(props) {
  const { nodes, materials } = useGLTF('/restaurant.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['700-nw_ovcol81592bcolpic05contpic10']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.beige_004} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.beige_004_Wall_Entity_Material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.beige_005_Wall_Entity_Material} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.beige_006_Wall_Entity_Material} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.blanc_001} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.bleu_002} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.bleu_004} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.bleu_012} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.bois_046} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.bois_054} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.bois_055} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.bois_089_Room_Entity_Material} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.bois_110_Room_Entity_Material} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.d671effe7f2cd3fb8e0c119e09825243} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.eames_chair_dining_2____eames_chair_dinning_bmetal} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.eames_chair_dining_2____eames_chair_dinning_bwood} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.enduit_004_Room_Entity_Material} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.enduit_004_Wall_Entity_Material} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.faience_041_ovcol999999colpic12contpic01_Room_Entity_Material} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.gris_004} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.gris_004_Wall_Entity_Material} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.hotte_001___material__177} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.hotte_001___material__178} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.hotte_001___material__179} />
        <mesh geometry={nodes.Object_27.geometry} material={materials['kisspng-pizza-knight-italian-cuisine-vegetarian-cuisine-fo-food-5ab8d54f287396']} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.kitchen_classic_style_base_cabinet_007___phong2sg} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.kitchen_classic_style_base_cabinet_007___phong8sg} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.kitchen_classic_style_base_corner_001___phong2sg} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.kitchen_classic_style_base_corner_001___phong8sg} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.kitchen_classic_style_dishwasher_000___phong5sg} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.kitchen_classic_style_dishwasher_000___phong8sg} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.kitchen_classic_style_dishwasher_000___phong9sg} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.kitchen_classic_style_double_oven_000___phong4sg} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.kitchen_classic_style_double_oven_000___phong5sg} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.kitchen_classic_style_double_oven_000___phong6sg} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.kitchen_classic_style_double_oven_000___phong7sg} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.kitchen_classic_style_double_oven_000___vitre} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.lambris_ext_003} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.lambris_ext_004} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.lavabo_004___lambert3sg} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.lavabo_004___phong1sg} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.makaroniiztverdixsortovpshenitsikakievib_7ff8e298} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.meridienne_001___bis_mat_metalbasique004sg} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.meridienne_001___mat_tissus078_bissg} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.metal_rouille} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.mur_vegetal_off___phong150} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.mur_vegetal_off___phong151} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.mur_vegetal_off___phong30} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.mur_vegetal_off___phong31} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.ocre_001_Wall_Entity_Material} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.orange_003} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.pack_002_sdb_deroule_papier___01___defaulta} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.pack_002_sdb_deroule_papier___01___defaulte} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.pack_002_sdb_deroule_papier___01___defaultz} />
        <mesh geometry={nodes.Object_57.geometry} material={materials.pack_003_cuisine_001_table___mat_pack_003_cuisine_001_table_tablepieds} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.pack_004_cuisine_001_chaise___pied} />
        <mesh geometry={nodes.Object_59.geometry} material={materials.pack_004_cuisine_001_chaise___rond} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.pack_004_cuisine_001_chaise___tour} />
        <mesh geometry={nodes.Object_61.geometry} material={materials.pack_004_cuisine_001_chaise___tubes} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.pack_004_salon_002_tableau___enduit1} />
        <mesh geometry={nodes.Object_63.geometry} material={materials.pack_005_salle_a_manger_armoire___nopaint_bouteilles} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.pack_005_salle_a_manger_armoire___poignees} />
        <mesh geometry={nodes.Object_65.geometry} material={materials.plante_interieur_off___bis_palmier_tronc2} />
        <mesh geometry={nodes.Object_66.geometry} material={materials.plante_interieur_off___phong56} />
        <mesh geometry={nodes.Object_67.geometry} material={materials.plante_interieur_off___phong57} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.plante_interieur_off___phong80} />
        <mesh geometry={nodes.Object_69.geometry} material={materials.porte_009___d} />
        <mesh geometry={nodes.Object_70.geometry} material={materials.porte_009___p} />
        <mesh geometry={nodes.Object_71.geometry} material={materials.porte_022___mat_vitresg} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.poubelle_002___phong1sg} />
        <mesh geometry={nodes.Object_73.geometry} material={materials.poubelle_002___poubelle} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.s1200_3} />
        <mesh geometry={nodes.Object_75.geometry} material={materials.tissus_078} />
        <mesh geometry={nodes.Object_76.geometry} material={materials.tissus_089} />
        <mesh geometry={nodes.Object_77.geometry} material={materials.tissus_089_ovcola0a3cccolpic00contpic03} />
        <mesh geometry={nodes.Object_78.geometry} material={materials.tissus_096} />
        <mesh geometry={nodes.Object_79.geometry} material={materials.vase_fleur_off___phong94} />
        <mesh geometry={nodes.Object_80.geometry} material={materials.vitrine_000___mat_vitrine_verre} />
        <mesh geometry={nodes.Object_81.geometry} material={materials.wc_004___wc_004_blinn1sg} />
        <mesh geometry={nodes.Object_82.geometry} material={materials.wc_004___wc_004_blinn3sg} />
        <mesh geometry={nodes.Object_83.geometry} material={materials.ws13d0020} />
        <mesh geometry={nodes.Object_84.geometry} material={materials['--_ovcol6b5a2ecolpic06contpic09']} />
        <mesh geometry={nodes.Object_85.geometry} material={materials['-------76810378']} />
      </group>
    </group>
  )
}

useGLTF.preload('/restaurant.glb')
